services:
    laravel.test:
        build:
            context: ./docker/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            # SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80"
        volumes:
            - '.:/var/www/html'
        network_mode: host
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        network_mode: host
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        volumes:
            - 'sail-redis:/data'
        network_mode: host
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    # ORIGIN SERVICES
    origin-srs:
        image: ossrs/srs:6
        environment:
            SRS_HTTP_PORT: 8082
        network_mode: host
        volumes:
            - ./docker/origin-srs/origin.conf:/usr/local/srs/conf/custom.conf:ro
        command: ./objs/srs -c /usr/local/srs/conf/custom.conf
        depends_on:
            - laravel.test
        restart: unless-stopped
    
    # Origin FFmpeg HLS Transcoder - Creates multi-bitrate HLS from SRS
    origin-ffmpeg-hls:
        build:
            context: ./docker/ffmpeg-hls
            dockerfile: Dockerfile
        environment:
            SRS_API_URL: http://localhost:1985/api/v1
            SRS_RTMP_URL: rtmp://localhost:1935
            OUTPUT_BASE_DIR: /var/www/hls/live
            CHECK_INTERVAL: 5
        volumes:
            # HLS output directory shared with origin-nginx
            - hls-content:/var/www/hls
        network_mode: host
        restart: unless-stopped
        depends_on:
            - origin-srs
    
    # Origin Nginx - Serves HLS with auth_request authentication
    origin-nginx:
        image: nginx:alpine
        volumes:
            - ./docker/origin-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - hls-content:/var/www/hls:ro
            - origin-nginx-cache:/var/cache/nginx
            - origin-nginx-logs:/var/log/nginx
        network_mode: host
        depends_on:
            - laravel.test
            - origin-ffmpeg-hls
        healthcheck:
            test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8083/health"]
            interval: 10s
            timeout: 5s
            retries: 3
        restart: unless-stopped
    
    # Origin Caddy - SSL termination for origin (port 8070 for local, 8080 in production)
    origin-caddy:
        image: caddy:alpine
        environment:
            DOMAIN: '${APP_URL:-localhost}'
            CADDY_PORT: 8070
            NGINX_ORIGIN_PORT: 8083
        volumes:
            - ./docker/origin-caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - origin-caddy-data:/data
            - origin-caddy-config:/config
            - origin-caddy-logs:/var/log/caddy
        network_mode: host
        depends_on:
            - origin-nginx
        restart: unless-stopped
    # EDGE SERVICES
    # Edge Nginx - Proxies and caches content from origin Caddy
    edge-nginx:
        image: nginx:alpine
        volumes:
            - ./docker/edge-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - edge-nginx-cache:/var/cache/nginx
            - edge-nginx-logs:/var/log/nginx
        network_mode: host
        depends_on:
            - laravel.test
            - origin-caddy
        healthcheck:
            test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/health"]
            interval: 10s
            timeout: 5s
            retries: 3
        restart: unless-stopped

    # Edge Caddy - SSL termination for edge server
    edge-caddy:
        image: caddy:alpine
        environment:
            DOMAIN: '${APP_URL:-localhost}'
            CADDY_PORT: 8080
            NGINX_EDGE_PORT: 8081
        volumes:
            - ./docker/edge-caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy-data:/data
            - caddy-config:/config
            - caddy-logs:/var/log/caddy
        network_mode: host
        restart: unless-stopped
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    # Origin volumes
    hls-content:
        driver: local
    origin-nginx-cache:
        driver: local
    origin-nginx-logs:
        driver: local
    origin-caddy-data:
        driver: local
    origin-caddy-config:
        driver: local
    origin-caddy-logs:
        driver: local
    # Edge volumes
    edge-nginx-cache:
        driver: local
    edge-nginx-logs:
        driver: local
    caddy-data:
        driver: local
    caddy-config:
        driver: local
    caddy-logs:
        driver: local
